### ISSUE TITLE
Error querying the DB

### ISSUE THREAD

**Issue by oliverfn** [subsquid/hydra-template#5]
## System

* Node: 14.17.4
* Yarn: 1.22.11
* macOS 11.2.1
* PostgreSQL 13.3 (Postgres.app 2.4.3)

### dev-dependencies

*    `@subsquid/hydra-cli": "3.1.0-alpha.1"`
*    `@subsquid/hydra-processor": "3.1.0-alpha.1"`
*    `@subsquid/hydra-typegen": "3.1.0-alpha.1"`

##  Reproduce

1. install latest stable nodejs/yarn
2. install and setup local postgres server (postgres.app)
3. clone the template repo / use it as template on own repo
4. `yarn && bootstrap`
5. `yarn typegen`
6.  `yarn mappings:build`
7.  `yarn query-node:start:dev`: tested the example query:
```graphql
query {
  accounts(limit: 5, where: { wallet_eq: "5HKcLj5vuexs9K6jAGdjErKijVFciLQzWBoJtj7cmrqe6GpB" }) {
     id
     balance
     wallet
     historicalBalances {
       balance
       timestamp
     }
  }  
}
```
**response**:
```graphql
{
  "data": {
    "accounts": []
  }
}
```
no results because processor hasn't migrated any data to postgresdb yet. ok, thus far.
8. `yarn processor:start` -> hydra-template-db and correct tables are created, I checked using PGadmin.
9. when I caught up to latest block, started the query-node again and ran the same query, the query node shuts down with following response and the associated error log included in "Logs"-section (same case, if I remove the "where"-statement). 
```graphql
{
  "error": "Failed to fetch. Please check your connection"
}
```
I assume, as soon as results may be available from the db it crashes on access. If I pass a non-existent address or just an empty string to the query, I will get the empty response (`"accounts": []`) again, obviously without the query-node crashing.

## Logs

```bash
'🚀 Server ready at http://localhost:4000/graphql'
query: SELECT "account"."id" AS "account_id", "account"."wallet" AS "account_wallet", "account"."balance" AS "account_balance" FROM "account" "account" WHERE "account"."wallet" = $1 AND "account"."deleted_at" IS NULL LIMIT 5 -- PARAMETERS: ["5HKcLj5vuexs9K6jAGdjErKijVFciLQzWBoJtj7cmrqe6GpB"]

/Users/user/hydra-template/generated/graphql-server/node_modules/dataloader/index.js:246
  var batchPromise = batchLoadFn(keys);
                     ^
TypeError: Cannot read property 'loadManyToManyRelationIdsAndGroup' of undefined
    at /Users/user/hydra-template/generated/graphql-server/node_modules/warthog/src/middleware/DataLoaderMiddleware.ts:40:18
    at dispatchQueueBatch (/Users/user/hydra-template/generated/graphql-server/node_modules/dataloader/index.js:246:22)
    at dispatchQueue (/Users/user/hydra-template/generated/graphql-server/node_modules/dataloader/index.js:233:5)
    at /Users/user/hydra-template/generated/graphql-server/node_modules/dataloader/index.js:70:20
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[ 'Closing the subscriber' ]
```

**Comment by oliverfn** [comment]
Not running into this issue using the 4.0.0 dev-dependencies.

**Comment by dzhelezov** [comment]
Closing for now
